from enum import StrEnum


class EstadoProyecto(StrEnum):
    SUBIDO = "SUBIDO"
    PENDIENTE_ANALISIS = "PENDIENTE_ANALISIS"
    ANALIZANDO_GRAPHIFY = "ANALIZANDO_GRAPHIFY"
    GRAPHIFY_COMPLETADO = "GRAPHIFY_COMPLETADO"
    ERROR_ANALISIS = "ERROR_ANALISIS"


class EstadoDocumentacion(StrEnum):
    PENDIENTE = "PENDIENTE"
    GENERANDO_DOCUMENTACION = "GENERANDO_DOCUMENTACION"
    DOCUMENTACION_COMPLETADA = "DOCUMENTACION_COMPLETADA"
    ERROR_DOCUMENTACION = "ERROR_DOCUMENTACION"